server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://qwen3-tts-api:8888/api/;
    }
    location /reference-audio {
        proxy_pass http://qwen3-tts-api:8888/reference-audio;
    }
    location /speakers {
        proxy_pass http://qwen3-tts-api:8888/speakers;
    }
    location /info {
        proxy_pass http://qwen3-tts-api:8888/info;
    }
}
